service: skazka-serverless-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    NODE_ENV: production
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

functions:
  app:
    handler: index.handler
    events:
      - httpApi: '*'
