sudo: required

language: node_js

node_js:
  - "10"
  - "12"
  - "13"

cache: yarn

services:
  - docker

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop

install:
  - npm i -g yarn lerna jest
  - lerna bootstrap

script:
  - yarn test
